name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build backend
        run: npm run build

      - name: Install http-server
        run: npm install -g http-server

      - name: Start backend in background
        run: |
          nohup npm run start &  
          sleep 10 

      - name: Wait for backend to be ready
        run: |
          timeout 60 sh -c 'until curl -s http://localhost:8080/health; do sleep 5; done'

      - name: Start frontend in background
        run: |
          nohup npx http-server ./js_fake_info_frontend -p 3000 &
          sleep 5

      - name: Run Postman tests
        run: |
          cd PostmanTests
          newman run API_test.postman_collection.json -e TestingManda.postman_environment.json

      - name: Run Vitest tests
        run: npm run test:ci

      - name: Run Cypress E2E tests
        run: |
          cd E2ETests
          npx cypress run
        env:
          CYPRESS_BASE_URL: http://localhost:3000

      - name: Stop http-server
        if: always()
        run: pkill -f http-server