name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Start backend in background
        run: |
          nohup npm run start &  
          sleep 10 

      - name: Wait for backend to be ready
        run: |
          timeout 60 sh -c 'until curl -s http://localhost:8080/health; do sleep 5; done'

      - name: Run Postman tests
        run: |
          cd PostmanTests
          newman run API_test.postman_collection.json -e TestingManda.postman_environment.json

      - name: Run Vitest tests
        run: npm run test:ci